sudo: required

services:
  - docker

languarge: bash 

env:
  - NodeVersion=18.12.1
  - NodeVersion=18.13.0
  - NodeVersion=19.14.0

script:
  - echo "Not implemented"

deploy:
  provider: script
  script: bash scripts/build-push.sh
  on:
    branch: master
