sudo: required

services:
  - docker

languarge: bash 

env:
  - NodeMajor=12
  - NodeMajor=14
  - NodeMajor=15

script:
  - echo "Not implemented"

deploy:
  provider: script
  script: bash scripts/build-push.sh
  on:
    branch: master
