sudo: required

services:
  - docker

languarge: bash 

env:
  - NodeMajor=18
  - NodeMajor=19

script:
  - echo "Not implemented"

deploy:
  provider: script
  script: bash scripts/build-push.sh
  on:
    branch: master
